# Generated by Django 4.0.5 on 2022-08-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_post_img_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='posted_date',
            field=models.DateTimeField(null=True),
        ),
    ]
